### ISSUE TITLE
singularity links do not resolve

### ISSUE THREAD

**Issue by pbedenbaugh** [emefff/Code-Aster-MPI-in-Singularity-of-SM2021#2]
singularity pull ... results in "... project emefff not found"

**Comment by emefff** [comment]
Hello,
somehow the container was deleted by Sylabs, I will try to upload it again in the next days....
emefff

**Comment by emefff** [comment]
Hello,
container is up again, support said they 'inadvertently deleted this project as it was mistaken for another one of our users''.
Please try if it works, thank you,
Mario.

**Comment by pbedenbaugh** [comment]
Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
